### ISSUE TITLE
Impossible de faire un post de type "lien" et impossible d'accéder à l'affichage d'un commentaire

### ISSUE THREAD

**Issue by stephmnt** [Brachamul/edem#16]
Quand tu cliques là
![capture](https://cloud.githubusercontent.com/assets/8942685/7599354/8d1ae276-f901-11e4-9838-6386c15aa288.png)
Ou là
![capture-1](https://cloud.githubusercontent.com/assets/8942685/7599352/8d19d67e-f901-11e4-9f95-72ef718a3176.png)
Ça donne ça
![capture-2](https://cloud.githubusercontent.com/assets/8942685/7599353/8d1aad92-f901-11e4-9c0e-3c70777e6618.png)
Voilà :)

**Comment by Brachamul** [comment]
C'est résolu !
